-- CreateTable
CREATE TABLE "TP_MAPAS" (
    "COD_MAPA_ID" TEXT NOT NULL,
    "COD_GRUPO_ID" TEXT NOT NULL,
    "COD_NIVEL_COMPATILHAMENTO" TEXT NOT NULL,
    "NOM_NOME_MAPA" TEXT NOT NULL,
    "DSC_TITULO" TEXT NOT NULL,
    "DSC_DESCRICAO" TEXT NOT NULL,
    "DSC_BOUNDING_BOX" TEXT,
    "COD_USUARIO_CRIACAO" TEXT NOT NULL,
    "COD_USUARIO_ULTIMA_ALTERACAO" TEXT,
    "COD_USUARIO_EXCLUSAO" TEXT,
    "DHS_INCLUSAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DHS_ULTIMA_ALTERACAO" TIMESTAMP(3),
    "DHS_EXCLUSAO" TIMESTAMP(3),

    CONSTRAINT "TP_MAPAS_pkey" PRIMARY KEY ("COD_MAPA_ID")
);

-- CreateTable
CREATE TABLE "TR_MAPAS_CAMADAS" (
    "COD_MAPA_CAMADA_ID" TEXT NOT NULL,
    "COD_CAMADA_ID" TEXT NOT NULL,
    "COD_MAPA_ID" TEXT NOT NULL,
    "NUM_ORDEM_RENDERIZACAO" INTEGER NOT NULL,

    CONSTRAINT "TR_MAPAS_CAMADAS_pkey" PRIMARY KEY ("COD_MAPA_CAMADA_ID")
);

-- CreateTable
CREATE TABLE "TD_MAPAS_CAMADAS_FILTROS" (
    "COD_FILTRO_ID" TEXT NOT NULL,
    "COD_MAPA_CAMADA_ID" TEXT NOT NULL,
    "DSC_FILTRO" TEXT NOT NULL,

    CONSTRAINT "TD_MAPAS_CAMADAS_FILTROS_pkey" PRIMARY KEY ("COD_FILTRO_ID")
);

-- CreateTable
CREATE TABLE "TR_MAPAS_CAMADAS_RASTER" (
    "COD_MAPA_CAMADA_RASTER_ID" TEXT NOT NULL,
    "COD_CAMADA_RASTER_ID" TEXT NOT NULL,
    "COD_MAPA_ID" TEXT NOT NULL,
    "NUM_ORDEM_RENDERIZACAO" INTEGER NOT NULL,

    CONSTRAINT "TR_MAPAS_CAMADAS_RASTER_pkey" PRIMARY KEY ("COD_MAPA_CAMADA_RASTER_ID")
);

-- CreateTable
CREATE TABLE "TP_USER" (
    "COD_USER_ID" TEXT NOT NULL,
    "NOM_USER" TEXT NOT NULL,
    "COD_PERFIL_USER" TEXT NOT NULL,
    "DSC_EMAIL" TEXT NOT NULL,
    "DSC_PASSWORD" TEXT NOT NULL,
    "DHS_ULTIMA_AUTENTICACAO" TIMESTAMP(3),
    "COD_USUARIO_CRIACAO" TEXT,
    "COD_USUARIO_ULTIMA_ALTERACAO" TEXT,
    "COD_USUARIO_EXCLUSAO" TEXT,
    "DHS_EXCLUSAO" TIMESTAMP(3),
    "DHS_INCLUSAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DHS_ULTIMA_ALTERACAO" TIMESTAMP(3),
    "DSC_EMAIL_VERIFICATION_TOKEN" TEXT,
    "DSC_EMAIL_VERIFICATION_EXPIRES" TIMESTAMP(3),
    "BOL_EMAIL_VERIFIED" BOOLEAN NOT NULL DEFAULT false,
    "DSC_RESET_PASSWORD_TOKEN" TEXT,
    "DHS_EXPIRES_RESET_PASSWORD" TIMESTAMP(3),

    CONSTRAINT "TP_USER_pkey" PRIMARY KEY ("COD_USER_ID")
);

-- CreateTable
CREATE TABLE "TA_PERFIL_USER" (
    "DSC_PERFIL" TEXT NOT NULL,
    "COD_PERFIL_USER" TEXT NOT NULL,

    CONSTRAINT "TA_PERFIL_USER_pkey" PRIMARY KEY ("COD_PERFIL_USER")
);

-- CreateTable
CREATE TABLE "TA_TEMAS" (
    "COD_TEMA_ID" TEXT NOT NULL,
    "NOM_NOME_TEMA" TEXT NOT NULL,
    "COD_USUARIO_CRIACAO" TEXT,
    "COD_USUARIO_ULTIMA_ALTERACAO" TEXT,
    "COD_USUARIO_EXCLUSAO" TEXT,
    "DHS_EXCLUSAO" TIMESTAMP(3),
    "DHS_INCLUSAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DHS_ULTIMA_ALTERACAO" TIMESTAMP(3),

    CONSTRAINT "TA_TEMAS_pkey" PRIMARY KEY ("COD_TEMA_ID")
);

-- CreateTable
CREATE TABLE "TA_GRUPO" (
    "COD_GRUPO_ID" TEXT NOT NULL,
    "NOM_NOME_GRUPO" TEXT NOT NULL,
    "COD_USUARIO_CRIACAO" TEXT NOT NULL,
    "COD_USUARIO_ULTIMA_ALTERACAO" TEXT,
    "COD_USUARIO_EXCLUSAO" TEXT,
    "DHS_EXCLUSAO" TIMESTAMP(3),
    "COD_TEMA_ID" TEXT NOT NULL,
    "DHS_INCLUSAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DHS_ULTIMA_ALTERACAO" TIMESTAMP(3),

    CONSTRAINT "TA_GRUPO_pkey" PRIMARY KEY ("COD_GRUPO_ID")
);

-- CreateTable
CREATE TABLE "TA_FOLDERS" (
    "COD_FOLDER_ID" TEXT NOT NULL,
    "DSC_FOLDER" TEXT NOT NULL,
    "COD_USUARIO_CRIACAO" TEXT NOT NULL,

    CONSTRAINT "TA_FOLDERS_pkey" PRIMARY KEY ("COD_FOLDER_ID")
);

-- CreateTable
CREATE TABLE "TP_CAMADAS" (
    "COD_CAMADA_ID" TEXT NOT NULL,
    "NOM_NOME" TEXT NOT NULL,
    "DSC_TITULO" TEXT NOT NULL,
    "DSC_DESCRICAO" TEXT NOT NULL,
    "DSC_LINK_METADADOS" TEXT NOT NULL,
    "TXT_TERMOS_DE_USO" TEXT NOT NULL,
    "COD_NIVEL_COMPATILHAMENTO" TEXT NOT NULL,
    "COD_GRUPO_ID" TEXT NOT NULL,
    "TXT_TAGS" TEXT NOT NULL,
    "COD_PACOTE_CONCEITUAL_ID" TEXT NOT NULL,
    "DSC_FONTE_DADOS_CAMADA" TEXT NOT NULL,
    "DSC_BOUNDING_BOX" TEXT,
    "COD_USUARIO_CRIACAO" TEXT NOT NULL,
    "COD_USUARIO_ULTIMA_ALTERACAO" TEXT,
    "COD_USUARIO_EXCLUSAO" TEXT,
    "FLG_CAMADA_ATIVA" BOOLEAN NOT NULL DEFAULT true,
    "DHS_EXCLUSAO" TIMESTAMP(3),
    "DHS_INCLUSAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DHS_ULTIMA_ALTERACAO" TIMESTAMP(3),

    CONSTRAINT "TP_CAMADAS_pkey" PRIMARY KEY ("COD_CAMADA_ID")
);

-- CreateTable
CREATE TABLE "TP_CAMADAS_RASTER" (
    "COD_CAMADA_RASTER_ID" TEXT NOT NULL,
    "NOM_NOME" TEXT NOT NULL,
    "DSC_FONTE_DADOS_CAMADA" TEXT,
    "DSC_TITULO" TEXT NOT NULL,
    "DSC_DESCRICAO" TEXT NOT NULL,
    "DSC_LINK_METADADOS" TEXT NOT NULL,
    "TXT_TERMOS_DE_USO" TEXT NOT NULL,
    "COD_NIVEL_COMPATILHAMENTO" TEXT NOT NULL,
    "COD_GRUPO_ID" TEXT NOT NULL,
    "TXT_TAGS" TEXT NOT NULL,
    "DSC_BOUNDING_BOX" TEXT,
    "COD_USUARIO_CRIACAO" TEXT NOT NULL,
    "COD_USUARIO_ULTIMA_ALTERACAO" TEXT,
    "COD_USUARIO_EXCLUSAO" TEXT,
    "FLG_CAMADA_ATIVA" BOOLEAN NOT NULL DEFAULT true,
    "DHS_EXCLUSAO" TIMESTAMP(3),
    "DHS_INCLUSAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DHS_ULTIMA_ALTERACAO" TIMESTAMP(3),

    CONSTRAINT "TP_CAMADAS_RASTER_pkey" PRIMARY KEY ("COD_CAMADA_RASTER_ID")
);

-- CreateTable
CREATE TABLE "TR_FOLDERS_CAMADAS" (
    "COD_FOLDER_CAMADADA_ID" TEXT NOT NULL,
    "COD_FOLDER_ID" TEXT NOT NULL,
    "COD_CAMADA_ID" TEXT NOT NULL,

    CONSTRAINT "TR_FOLDERS_CAMADAS_pkey" PRIMARY KEY ("COD_FOLDER_CAMADADA_ID")
);

-- CreateTable
CREATE TABLE "TR_FOLDERS_CAMADAS_RASTER" (
    "COD_FOLDER_CAMADADA_RASTER_ID" TEXT NOT NULL,
    "COD_FOLDER_ID" TEXT NOT NULL,
    "COD_CAMADA_RASTER_ID" TEXT NOT NULL,

    CONSTRAINT "TR_FOLDERS_CAMADAS_RASTER_pkey" PRIMARY KEY ("COD_FOLDER_CAMADADA_RASTER_ID")
);

-- CreateTable
CREATE TABLE "TR_FOLDERS_MAPAS" (
    "COD_FOLDER_MAPA_ID" TEXT NOT NULL,
    "COD_FOLDER_ID" TEXT NOT NULL,
    "COD_MAPA_ID" TEXT NOT NULL,

    CONSTRAINT "TR_FOLDERS_MAPAS_pkey" PRIMARY KEY ("COD_FOLDER_MAPA_ID")
);

-- CreateTable
CREATE TABLE "TA_PACOTES_CONCEITUAIS" (
    "COD_PACOTE_CONCEITUAL_ID" TEXT NOT NULL,
    "NOM_NOME_PACOTE_CONCEITUAL" TEXT NOT NULL,
    "DSC_TITULO" TEXT NOT NULL,
    "DSC_HOST" TEXT NOT NULL,
    "DSC_PORT" TEXT NOT NULL,
    "DSC_DATABASE" TEXT NOT NULL,
    "DSC_SCHEMA" TEXT NOT NULL,
    "DSC_USER" TEXT NOT NULL,
    "DSC_PASSWORD" TEXT NOT NULL,
    "COD_USUARIO_CRIACAO" TEXT NOT NULL,
    "COD_USUARIO_ULTIMA_ALTERACAO" TEXT,
    "COD_USUARIO_EXCLUSAO" TEXT,
    "DHS_EXCLUSAO" TIMESTAMP(3),
    "DHS_INCLUSAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DHS_ULTIMA_ALTERACAO" TIMESTAMP(3),

    CONSTRAINT "TA_PACOTES_CONCEITUAIS_pkey" PRIMARY KEY ("COD_PACOTE_CONCEITUAL_ID")
);

-- CreateTable
CREATE TABLE "TA_NIVEL_COMPARTILHAMENTO" (
    "COD_NIVEL_COMPATILHAMENTO" TEXT NOT NULL,
    "DSC_NIVEL_COMPATILHAMENTO" TEXT NOT NULL,
    "COD_USUARIO_CRIACAO" TEXT NOT NULL,
    "COD_USUARIO_ULTIMA_ALTERACAO" TEXT,
    "COD_USUARIO_EXCLUSAO" TEXT,
    "DHS_EXCLUSAO" TIMESTAMP(3),
    "DHS_INCLUSAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DHS_ULTIMA_ALTERACAO" TIMESTAMP(3),

    CONSTRAINT "TA_NIVEL_COMPARTILHAMENTO_pkey" PRIMARY KEY ("COD_NIVEL_COMPATILHAMENTO")
);

-- CreateTable
CREATE TABLE "TA_INSTITUICOES" (
    "COD_INSTITUICAO_ID" TEXT NOT NULL,
    "NOM_INTITUICAO" TEXT NOT NULL,
    "COD_USUARIO_CRIACAO" TEXT NOT NULL,
    "COD_USUARIO_ULTIMA_ALTERACAO" TEXT,
    "COD_USUARIO_EXCLUSAO" TEXT,
    "DHS_EXCLUSAO" TIMESTAMP(3),
    "DHS_INCLUSAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DHS_ULTIMA_ALTERACAO" TIMESTAMP(3),

    CONSTRAINT "TA_INSTITUICOES_pkey" PRIMARY KEY ("COD_INSTITUICAO_ID")
);

-- CreateTable
CREATE TABLE "TP_ATRIBUTOS" (
    "COD_ATRIBUTO_ID" TEXT NOT NULL,
    "COD_CAMADA_ID" TEXT NOT NULL,
    "NOM_NOME_ATRIBUTO" TEXT NOT NULL,
    "DSC_LABEL_ATRIBUTO" TEXT,
    "DSC_TIPO" TEXT,
    "NUM_TAMANHO" TEXT,
    "FLG_VISIVEL" BOOLEAN NOT NULL,
    "TXT_DESCRICAO" TEXT,
    "COD_USUARIO_CRIACAO" TEXT NOT NULL,
    "COD_USUARIO_ULTIMA_ALTERACAO" TEXT,
    "COD_USUARIO_EXCLUSAO" TEXT,
    "DHS_EXCLUSAO" TIMESTAMP(3),
    "DHS_INCLUSAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DHS_ULTIMA_ALTERACAO" TIMESTAMP(3),

    CONSTRAINT "TP_ATRIBUTOS_pkey" PRIMARY KEY ("COD_ATRIBUTO_ID")
);

-- CreateTable
CREATE TABLE "TR_CREDITOS" (
    "COD_INSTITUICAO_ID" TEXT NOT NULL,
    "COD_CAMADA_ID" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "TP_LOG_CAMADAS" (
    "COD_LOG_ID" TEXT NOT NULL,
    "COD_CAMADA_ID" TEXT NOT NULL,
    "DHS_ACESSO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TP_LOG_CAMADAS_pkey" PRIMARY KEY ("COD_LOG_ID")
);

-- CreateTable
CREATE TABLE "TP_LOG_CAMADAS_RASTER" (
    "COD_LOG_ID" TEXT NOT NULL,
    "COD_CAMADA_RASTER_ID" TEXT NOT NULL,
    "DHS_ACESSO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TP_LOG_CAMADAS_RASTER_pkey" PRIMARY KEY ("COD_LOG_ID")
);

-- CreateTable
CREATE TABLE "TP_LOG_MAPAS" (
    "COD_LOG_ID" TEXT NOT NULL,
    "COD_MAPA_ID" TEXT NOT NULL,
    "DHS_ACESSO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TP_LOG_MAPAS_pkey" PRIMARY KEY ("COD_LOG_ID")
);

-- CreateTable
CREATE TABLE "TP_FAVORITOS_CAMADAS" (
    "COD_FAVORITO_ID" TEXT NOT NULL,
    "COD_USER_ID" TEXT NOT NULL,
    "COD_CAMADA_ID" TEXT NOT NULL,
    "DHS_INCLUSAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TP_FAVORITOS_CAMADAS_pkey" PRIMARY KEY ("COD_FAVORITO_ID")
);

-- CreateTable
CREATE TABLE "TP_FAVORITOS_CAMADAS_RASTER" (
    "COD_FAVORITO_ID" TEXT NOT NULL,
    "COD_USER_ID" TEXT NOT NULL,
    "COD_CAMADA_RASTER_ID" TEXT NOT NULL,
    "DHS_INCLUSAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TP_FAVORITOS_CAMADAS_RASTER_pkey" PRIMARY KEY ("COD_FAVORITO_ID")
);

-- CreateTable
CREATE TABLE "TP_FAVORITOS_MAPAS" (
    "COD_FAVORITO_ID" TEXT NOT NULL,
    "COD_USER_ID" TEXT NOT NULL,
    "COD_MAPA_ID" TEXT NOT NULL,
    "DHS_INCLUSAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TP_FAVORITOS_MAPAS_pkey" PRIMARY KEY ("COD_FAVORITO_ID")
);

-- CreateTable
CREATE TABLE "TP_CONFIG" (
    "COD_CONFIG_ID" TEXT NOT NULL,
    "NUM_GRUPO_ORDER" INTEGER NOT NULL,
    "NUM_KEY_ORDER" INTEGER NOT NULL,
    "DSC_GRUPO_KEY" TEXT NOT NULL,
    "DSC_KEY" TEXT NOT NULL,
    "DSC_VALUE" TEXT,
    "COD_USUARIO_CRIACAO" TEXT NOT NULL,
    "COD_USUARIO_ULTIMA_ALTERACAO" TEXT,
    "COD_USUARIO_EXCLUSAO" TEXT,
    "DHS_EXCLUSAO" TIMESTAMP(3),
    "DHS_INCLUSAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DHS_ULTIMA_ALTERACAO" TIMESTAMP(3),

    CONSTRAINT "TP_CONFIG_pkey" PRIMARY KEY ("COD_CONFIG_ID")
);

-- CreateTable
CREATE TABLE "TP_COMPONENTE" (
    "COD_COMPONENTE_ID" TEXT NOT NULL,
    "NOM_NOME_COMPONENTE" TEXT NOT NULL,
    "DSC_DESCRICAO" TEXT,
    "JSON_CONFIGURACAO" JSONB NOT NULL,
    "FLG_HABILITADO" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "TP_COMPONENTE_pkey" PRIMARY KEY ("COD_COMPONENTE_ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "TP_USER_DSC_EMAIL_key" ON "TP_USER"("DSC_EMAIL");

-- CreateIndex
CREATE UNIQUE INDEX "TP_USER_DSC_EMAIL_VERIFICATION_TOKEN_key" ON "TP_USER"("DSC_EMAIL_VERIFICATION_TOKEN");

-- CreateIndex
CREATE UNIQUE INDEX "TP_USER_DSC_RESET_PASSWORD_TOKEN_key" ON "TP_USER"("DSC_RESET_PASSWORD_TOKEN");

-- CreateIndex
CREATE UNIQUE INDEX "TR_CREDITOS_COD_INSTITUICAO_ID_COD_CAMADA_ID_key" ON "TR_CREDITOS"("COD_INSTITUICAO_ID", "COD_CAMADA_ID");

-- CreateIndex
CREATE UNIQUE INDEX "TP_FAVORITOS_CAMADAS_COD_USER_ID_COD_CAMADA_ID_key" ON "TP_FAVORITOS_CAMADAS"("COD_USER_ID", "COD_CAMADA_ID");

-- CreateIndex
CREATE UNIQUE INDEX "TP_FAVORITOS_CAMADAS_RASTER_COD_USER_ID_COD_CAMADA_RASTER_I_key" ON "TP_FAVORITOS_CAMADAS_RASTER"("COD_USER_ID", "COD_CAMADA_RASTER_ID");

-- CreateIndex
CREATE UNIQUE INDEX "TP_FAVORITOS_MAPAS_COD_USER_ID_COD_MAPA_ID_key" ON "TP_FAVORITOS_MAPAS"("COD_USER_ID", "COD_MAPA_ID");

-- CreateIndex
CREATE UNIQUE INDEX "TP_CONFIG_DSC_KEY_key" ON "TP_CONFIG"("DSC_KEY");

-- AddForeignKey
ALTER TABLE "TP_MAPAS" ADD CONSTRAINT "TP_MAPAS_COD_GRUPO_ID_fkey" FOREIGN KEY ("COD_GRUPO_ID") REFERENCES "TA_GRUPO"("COD_GRUPO_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TR_MAPAS_CAMADAS" ADD CONSTRAINT "TR_MAPAS_CAMADAS_COD_CAMADA_ID_fkey" FOREIGN KEY ("COD_CAMADA_ID") REFERENCES "TP_CAMADAS"("COD_CAMADA_ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TR_MAPAS_CAMADAS" ADD CONSTRAINT "TR_MAPAS_CAMADAS_COD_MAPA_ID_fkey" FOREIGN KEY ("COD_MAPA_ID") REFERENCES "TP_MAPAS"("COD_MAPA_ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TD_MAPAS_CAMADAS_FILTROS" ADD CONSTRAINT "TD_MAPAS_CAMADAS_FILTROS_COD_MAPA_CAMADA_ID_fkey" FOREIGN KEY ("COD_MAPA_CAMADA_ID") REFERENCES "TR_MAPAS_CAMADAS"("COD_MAPA_CAMADA_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TR_MAPAS_CAMADAS_RASTER" ADD CONSTRAINT "TR_MAPAS_CAMADAS_RASTER_COD_CAMADA_RASTER_ID_fkey" FOREIGN KEY ("COD_CAMADA_RASTER_ID") REFERENCES "TP_CAMADAS_RASTER"("COD_CAMADA_RASTER_ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TR_MAPAS_CAMADAS_RASTER" ADD CONSTRAINT "TR_MAPAS_CAMADAS_RASTER_COD_MAPA_ID_fkey" FOREIGN KEY ("COD_MAPA_ID") REFERENCES "TP_MAPAS"("COD_MAPA_ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TP_USER" ADD CONSTRAINT "TP_USER_COD_PERFIL_USER_fkey" FOREIGN KEY ("COD_PERFIL_USER") REFERENCES "TA_PERFIL_USER"("COD_PERFIL_USER") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TA_GRUPO" ADD CONSTRAINT "TA_GRUPO_COD_TEMA_ID_fkey" FOREIGN KEY ("COD_TEMA_ID") REFERENCES "TA_TEMAS"("COD_TEMA_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TP_CAMADAS" ADD CONSTRAINT "TP_CAMADAS_COD_GRUPO_ID_fkey" FOREIGN KEY ("COD_GRUPO_ID") REFERENCES "TA_GRUPO"("COD_GRUPO_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TP_CAMADAS" ADD CONSTRAINT "TP_CAMADAS_COD_NIVEL_COMPATILHAMENTO_fkey" FOREIGN KEY ("COD_NIVEL_COMPATILHAMENTO") REFERENCES "TA_NIVEL_COMPARTILHAMENTO"("COD_NIVEL_COMPATILHAMENTO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TP_CAMADAS" ADD CONSTRAINT "TP_CAMADAS_COD_PACOTE_CONCEITUAL_ID_fkey" FOREIGN KEY ("COD_PACOTE_CONCEITUAL_ID") REFERENCES "TA_PACOTES_CONCEITUAIS"("COD_PACOTE_CONCEITUAL_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TP_CAMADAS_RASTER" ADD CONSTRAINT "TP_CAMADAS_RASTER_COD_GRUPO_ID_fkey" FOREIGN KEY ("COD_GRUPO_ID") REFERENCES "TA_GRUPO"("COD_GRUPO_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TP_CAMADAS_RASTER" ADD CONSTRAINT "TP_CAMADAS_RASTER_COD_NIVEL_COMPATILHAMENTO_fkey" FOREIGN KEY ("COD_NIVEL_COMPATILHAMENTO") REFERENCES "TA_NIVEL_COMPARTILHAMENTO"("COD_NIVEL_COMPATILHAMENTO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TR_FOLDERS_CAMADAS" ADD CONSTRAINT "TR_FOLDERS_CAMADAS_COD_CAMADA_ID_fkey" FOREIGN KEY ("COD_CAMADA_ID") REFERENCES "TP_CAMADAS"("COD_CAMADA_ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TR_FOLDERS_CAMADAS" ADD CONSTRAINT "TR_FOLDERS_CAMADAS_COD_FOLDER_ID_fkey" FOREIGN KEY ("COD_FOLDER_ID") REFERENCES "TA_FOLDERS"("COD_FOLDER_ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TR_FOLDERS_CAMADAS_RASTER" ADD CONSTRAINT "TR_FOLDERS_CAMADAS_RASTER_COD_CAMADA_RASTER_ID_fkey" FOREIGN KEY ("COD_CAMADA_RASTER_ID") REFERENCES "TP_CAMADAS_RASTER"("COD_CAMADA_RASTER_ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TR_FOLDERS_CAMADAS_RASTER" ADD CONSTRAINT "TR_FOLDERS_CAMADAS_RASTER_COD_FOLDER_ID_fkey" FOREIGN KEY ("COD_FOLDER_ID") REFERENCES "TA_FOLDERS"("COD_FOLDER_ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TR_FOLDERS_MAPAS" ADD CONSTRAINT "TR_FOLDERS_MAPAS_COD_FOLDER_ID_fkey" FOREIGN KEY ("COD_FOLDER_ID") REFERENCES "TA_FOLDERS"("COD_FOLDER_ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TR_FOLDERS_MAPAS" ADD CONSTRAINT "TR_FOLDERS_MAPAS_COD_MAPA_ID_fkey" FOREIGN KEY ("COD_MAPA_ID") REFERENCES "TP_MAPAS"("COD_MAPA_ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TP_ATRIBUTOS" ADD CONSTRAINT "TP_ATRIBUTOS_COD_CAMADA_ID_fkey" FOREIGN KEY ("COD_CAMADA_ID") REFERENCES "TP_CAMADAS"("COD_CAMADA_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TR_CREDITOS" ADD CONSTRAINT "TR_CREDITOS_COD_CAMADA_ID_fkey" FOREIGN KEY ("COD_CAMADA_ID") REFERENCES "TP_CAMADAS"("COD_CAMADA_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TR_CREDITOS" ADD CONSTRAINT "TR_CREDITOS_COD_INSTITUICAO_ID_fkey" FOREIGN KEY ("COD_INSTITUICAO_ID") REFERENCES "TA_INSTITUICOES"("COD_INSTITUICAO_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TP_LOG_CAMADAS" ADD CONSTRAINT "TP_LOG_CAMADAS_COD_CAMADA_ID_fkey" FOREIGN KEY ("COD_CAMADA_ID") REFERENCES "TP_CAMADAS"("COD_CAMADA_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TP_LOG_CAMADAS_RASTER" ADD CONSTRAINT "TP_LOG_CAMADAS_RASTER_COD_CAMADA_RASTER_ID_fkey" FOREIGN KEY ("COD_CAMADA_RASTER_ID") REFERENCES "TP_CAMADAS_RASTER"("COD_CAMADA_RASTER_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TP_LOG_MAPAS" ADD CONSTRAINT "TP_LOG_MAPAS_COD_MAPA_ID_fkey" FOREIGN KEY ("COD_MAPA_ID") REFERENCES "TP_MAPAS"("COD_MAPA_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TP_FAVORITOS_CAMADAS" ADD CONSTRAINT "TP_FAVORITOS_CAMADAS_COD_CAMADA_ID_fkey" FOREIGN KEY ("COD_CAMADA_ID") REFERENCES "TP_CAMADAS"("COD_CAMADA_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TP_FAVORITOS_CAMADAS_RASTER" ADD CONSTRAINT "TP_FAVORITOS_CAMADAS_RASTER_COD_CAMADA_RASTER_ID_fkey" FOREIGN KEY ("COD_CAMADA_RASTER_ID") REFERENCES "TP_CAMADAS_RASTER"("COD_CAMADA_RASTER_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TP_FAVORITOS_MAPAS" ADD CONSTRAINT "TP_FAVORITOS_MAPAS_COD_MAPA_ID_fkey" FOREIGN KEY ("COD_MAPA_ID") REFERENCES "TP_MAPAS"("COD_MAPA_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

