version: '3.8'
services:
  geoserver:
    build:
      context: .
      dockerfile: Dockerfile.geoserver
    container_name: geoserver-webgis
    ports:
      - "8080:8080"
    volumes:
      - data_geoserver:/opt/geoserver_data
      - upload_raster:/opt/geoserver_data/upload_raster
    environment:
      - GEOSERVER_DATA_DIR=/opt/geoserver_data
      - ENABLE_CORS=true
      - JAVA_OPTS=-Ds3.properties.location=/opt/geoserver_data/s3.properties -Xms1G -Xmx4G -XX:+UseG1GC -Djava.awt.headless=true -XX:+UseStringDeduplication -Dcom.amazonaws.internal.S3AbortableInputStream.level=ERROR -Daws.region=us-east-1 -Duser.home=/opt/geoserver_data -server -Dorg.geotools.referencing.forceXY=true
    networks:
      - webgis_network
    restart: always
    depends_on:
      - postgres

  postgres:
    container_name: postgres-webgis
    image: postgis/postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: webgis
      PGDATA: /data/postgres
    volumes:
      - data_postgres:/data/postgres
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - webgis_network
    restart: always

networks:
  webgis_network:
    driver: bridge

volumes:
  data_geoserver:
  data_postgres:
  upload_raster: