minio.s3.endpoint=http://minio:9000
minio.s3.user=vHWQPjUujJwsKuadTpBT
minio.s3.password=wjTlhKuV0yk2lpwarb9bBaWhyDO1atSXVty9JpK8
minio.region=us-east-1
aws.region=us-east-1
minio.s3.path-style=true
minio.usedefaulturlencoder=true
minio.s3.force-region=true
minio.s3.buffer-size=262144
minio.s3.connection.maximum=100
minio.s3.stream-retry-buffer-size=262144
minio.s3.disable-chunked-encoding=true
minio.s3.use-range-get=true
minio.s3.connection-timeout=30000
minio.s3.request-timeout=30000
minio.s3.socket-timeout=30000
minio.s3.max-retry=5
minio.s3.tcp-keep-alive=true
minio.s3.use-gzip=true
minio.s3.signing-region=us-east-1
minio.s3.disable-stream-abort=true
minio.s3.read-whole-file=true
minio.s3.stream-transfer-size=262144
minio.s3.chunk-size=262144