-- AlterTable
ALTER TABLE "TP_CAMADAS_RASTER" ADD COLUMN "DSC_SEED_STATUS" TEXT DEFAULT 'idle';
ALTER TABLE "TP_CAMADAS_RASTER" ADD COLUMN "NUM_SEED_PROGRESS" INTEGER DEFAULT 0;
ALTER TABLE "TP_CAMADAS_RASTER" ADD COLUMN "DSC_COG_PERFIL" VARCHAR(40);
