-- CreateTable
CREATE TABLE "TP_BASEMAPS" (
    "COD_BASEMAP_ID" TEXT NOT NULL,
    "NOM_NOME_BASEMAP" TEXT NOT NULL,
    "DSC_THUMBNAIL" TEXT,
    "DSC_SOURCE" TEXT NOT NULL,
    "TIP_BASEMAP" TEXT NOT NULL DEFAULT 'xyz',
    "JSON_WMS_PARAMS" JSONB,
    "NUM_ORDEM" INTEGER NOT NULL DEFAULT 0,
    "BOL_DEFAULT" BOOLEAN NOT NULL DEFAULT false,
    "FLG_ATIVO" BOOLEAN NOT NULL DEFAULT true,
    "COD_USUARIO_CRIACAO" TEXT NOT NULL,
    "COD_USUARIO_ULTIMA_ALTERACAO" TEXT,
    "COD_USUARIO_EXCLUSAO" TEXT,
    "DHS_EXCLUSAO" TIMESTAMP(3),
    "DHS_INCLUSAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DHS_ULTIMA_ALTERACAO" TIMESTAMP(3),

    CONSTRAINT "TP_BASEMAPS_pkey" PRIMARY KEY ("COD_BASEMAP_ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "TP_BASEMAPS_NOM_NOME_BASEMAP_key" ON "TP_BASEMAPS"("NOM_NOME_BASEMAP");
