version: '3.7'

services:
  frontend:
    image: "${DOCKER_IMAGE_TAG}"
    labels:
      - "br.com.cesan.app=gis"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8899:4200
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1024M
