# Handlers
handlers = java.util.logging.ConsoleHandler

# Handler configuration
java.util.logging.ConsoleHandler.level = INFO

# GeoServer logging settings
org.geoserver.level = INFO
org.geotools.level = ERROR
org.geotools.s3.S3Connector.level = OFF
com.amazonaws.internal.S3AbortableInputStream.level = OFF
com.amazonaws.services.s3.level = ERROR