-- AlterTable
ALTER TABLE "TP_USER" ADD COLUMN     "COD_ENTRA_OBJECT_ID" TEXT,
ADD COLUMN     "DSC_AUTH_PROVIDER" TEXT NOT NULL DEFAULT 'local',
ALTER COLUMN "DSC_PASSWORD" DROP NOT NULL;

-- CreateIndex
CREATE UNIQUE INDEX "TP_USER_COD_ENTRA_OBJECT_ID_key" ON "TP_USER"("COD_ENTRA_OBJECT_ID");
