-- CreateTable
CREATE TABLE "TP_PUBLICACOES_CAMADA" (
    "COD_PUBLICACAO_ID" TEXT NOT NULL,
    "COD_CAMADA_ID" TEXT NOT NULL,
    "DSC_OPERACAO" TEXT NOT NULL,
    "DSC_STATUS" TEXT NOT NULL,
    "DSC_ERROR_MSG" VARCHAR(500),
    "TXT_MUDANCAS" TEXT,
    "COD_USUARIO" TEXT NOT NULL,
    "DHS_PUBLICACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TP_PUBLICACOES_CAMADA_pkey" PRIMARY KEY ("COD_PUBLICACAO_ID")
);

-- CreateTable
CREATE TABLE "TP_PUBLICACOES_CAMADA_RASTER" (
    "COD_PUBLICACAO_ID" TEXT NOT NULL,
    "COD_CAMADA_RASTER_ID" TEXT NOT NULL,
    "DSC_OPERACAO" TEXT NOT NULL,
    "DSC_STATUS" TEXT NOT NULL,
    "DSC_ERROR_MSG" VARCHAR(500),
    "TXT_MUDANCAS" TEXT,
    "COD_USUARIO" TEXT NOT NULL,
    "DHS_PUBLICACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TP_PUBLICACOES_CAMADA_RASTER_pkey" PRIMARY KEY ("COD_PUBLICACAO_ID")
);

-- AddForeignKey
ALTER TABLE "TP_PUBLICACOES_CAMADA" ADD CONSTRAINT "TP_PUBLICACOES_CAMADA_COD_CAMADA_ID_fkey" FOREIGN KEY ("COD_CAMADA_ID") REFERENCES "TP_CAMADAS"("COD_CAMADA_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TP_PUBLICACOES_CAMADA_RASTER" ADD CONSTRAINT "TP_PUBLICACOES_CAMADA_RASTER_COD_CAMADA_RASTER_ID_fkey" FOREIGN KEY ("COD_CAMADA_RASTER_ID") REFERENCES "TP_CAMADAS_RASTER"("COD_CAMADA_RASTER_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
