-- CreateTable
CREATE TABLE "TR_CAMADAS_GRUPOS_ADICIONAIS" (
    "COD_CAMADA_ID" TEXT NOT NULL,
    "COD_GRUPO_ID" TEXT NOT NULL,
    "DHS_INCLUSAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TR_CAMADAS_GRUPOS_ADICIONAIS_pkey" PRIMARY KEY ("COD_CAMADA_ID","COD_GRUPO_ID")
);

-- CreateTable
CREATE TABLE "TR_CAMADAS_RASTER_GRUPOS_ADICIONAIS" (
    "COD_CAMADA_RASTER_ID" TEXT NOT NULL,
    "COD_GRUPO_ID" TEXT NOT NULL,
    "DHS_INCLUSAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TR_CAMADAS_RASTER_GRUPOS_ADICIONAIS_pkey" PRIMARY KEY ("COD_CAMADA_RASTER_ID","COD_GRUPO_ID")
);

-- CreateTable
CREATE TABLE "TR_MAPAS_GRUPOS_ADICIONAIS" (
    "COD_MAPA_ID" TEXT NOT NULL,
    "COD_GRUPO_ID" TEXT NOT NULL,
    "DHS_INCLUSAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TR_MAPAS_GRUPOS_ADICIONAIS_pkey" PRIMARY KEY ("COD_MAPA_ID","COD_GRUPO_ID")
);

-- AddForeignKey
ALTER TABLE "TR_CAMADAS_GRUPOS_ADICIONAIS" ADD CONSTRAINT "TR_CAMADAS_GRUPOS_ADICIONAIS_COD_CAMADA_ID_fkey" FOREIGN KEY ("COD_CAMADA_ID") REFERENCES "TP_CAMADAS"("COD_CAMADA_ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TR_CAMADAS_GRUPOS_ADICIONAIS" ADD CONSTRAINT "TR_CAMADAS_GRUPOS_ADICIONAIS_COD_GRUPO_ID_fkey" FOREIGN KEY ("COD_GRUPO_ID") REFERENCES "TA_GRUPO"("COD_GRUPO_ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TR_CAMADAS_RASTER_GRUPOS_ADICIONAIS" ADD CONSTRAINT "TR_CAMADAS_RASTER_GRUPOS_ADICIONAIS_COD_CAMADA_RASTER_ID_fkey" FOREIGN KEY ("COD_CAMADA_RASTER_ID") REFERENCES "TP_CAMADAS_RASTER"("COD_CAMADA_RASTER_ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TR_CAMADAS_RASTER_GRUPOS_ADICIONAIS" ADD CONSTRAINT "TR_CAMADAS_RASTER_GRUPOS_ADICIONAIS_COD_GRUPO_ID_fkey" FOREIGN KEY ("COD_GRUPO_ID") REFERENCES "TA_GRUPO"("COD_GRUPO_ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TR_MAPAS_GRUPOS_ADICIONAIS" ADD CONSTRAINT "TR_MAPAS_GRUPOS_ADICIONAIS_COD_MAPA_ID_fkey" FOREIGN KEY ("COD_MAPA_ID") REFERENCES "TP_MAPAS"("COD_MAPA_ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TR_MAPAS_GRUPOS_ADICIONAIS" ADD CONSTRAINT "TR_MAPAS_GRUPOS_ADICIONAIS_COD_GRUPO_ID_fkey" FOREIGN KEY ("COD_GRUPO_ID") REFERENCES "TA_GRUPO"("COD_GRUPO_ID") ON DELETE CASCADE ON UPDATE CASCADE;
