.registry_login:
  before_script:
    - >
      echo "${REGISTRY_PASS}" |
      docker login ${REGISTRY_HOST}
      --username ${REGISTRY_USER} --password-stdin

variables:
  GIT_SUBMODULE_STRATEGY: recursive

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
      variables:
        DEPLOY_ENVIRONMENT: "develop"
    - if: $CI_COMMIT_BRANCH == "staging"
      variables:
        DEPLOY_ENVIRONMENT: "staging"
    - if: $CI_COMMIT_BRANCH == "master"
      variables:
        DEPLOY_ENVIRONMENT: "production"

stages:
  - dockerize
  - deploy

dockerize:
  stage: dockerize
  extends: .registry_login
  script:
    - APP_VERSION=$(grep version package.json | awk -F \" '{print $4}')
    - DOCKER_IMAGE_TAG=registry.cesan.com.br/cesan/${CI_PROJECT_NAME}:${APP_VERSION}
    - echo "DOCKER_IMAGE_TAG=${DOCKER_IMAGE_TAG}" >> docker.env
    - echo "Building with API_URL=${API_URL}"
    - echo "Building with GEOSERVER_HOST=${GEOSERVER_HOST}"
    - |-
      docker image build \
        -t ${DOCKER_IMAGE_TAG} \
        -f docker/Dockerfile \
        --build-arg API_URL=${API_URL} \
        --build-arg ENVIRONMENT=${DEPLOY_ENVIRONMENT} \
        --build-arg RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY} \
        --build-arg GEOSERVER_HOST=${GEOSERVER_HOST} \
        --pull --no-cache .
    - docker image push ${DOCKER_IMAGE_TAG}
  artifacts:
    reports:
      dotenv: docker.env
  environment: ${DEPLOY_ENVIRONMENT}
  tags:
    - swarm

deploy:
  stage: deploy
  extends: .registry_login
  dependencies:
    - dockerize
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
    - if: $CI_COMMIT_BRANCH == "staging"
    - if: $CI_COMMIT_BRANCH == "master"
      when: manual
  script:
    - >
      docker --context $DEPLOY_ENVIRONMENT stack deploy \
        --detach=true \
        --with-registry-auth -c docker/stack.yml gis
  environment: ${DEPLOY_ENVIRONMENT}
  tags:
    - swarm