-- AlterTable
ALTER TABLE "TA_GRUPO" ADD COLUMN "COD_USUARIO_DONO" TEXT,
ADD COLUMN "DSC_VISIBILIDADE" TEXT NOT NULL DEFAULT 'organizacao',
ADD COLUMN "DSC_POLITICA_PARTICIPACAO" TEXT NOT NULL DEFAULT 'convite',
ADD COLUMN "BOL_MEMBROS_CONTRIBUEM" BOOLEAN NOT NULL DEFAULT false;

-- CreateTable
CREATE TABLE "TR_GRUPO_MEMBROS" (
    "COD_GRUPO_MEMBRO_ID" TEXT NOT NULL,
    "COD_GRUPO_ID" TEXT NOT NULL,
    "COD_USER_ID" TEXT NOT NULL,
    "DSC_STATUS" TEXT NOT NULL DEFAULT 'membro',
    "COD_USUARIO_CRIACAO" TEXT NOT NULL,
    "COD_USUARIO_ULTIMA_ALTERACAO" TEXT,
    "COD_USUARIO_EXCLUSAO" TEXT,
    "DHS_INCLUSAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DHS_ULTIMA_ALTERACAO" TIMESTAMP(3),
    "DHS_EXCLUSAO" TIMESTAMP(3),

    CONSTRAINT "TR_GRUPO_MEMBROS_pkey" PRIMARY KEY ("COD_GRUPO_MEMBRO_ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "TR_GRUPO_MEMBROS_COD_GRUPO_ID_COD_USER_ID_key" ON "TR_GRUPO_MEMBROS"("COD_GRUPO_ID", "COD_USER_ID");

-- AddForeignKey
ALTER TABLE "TR_GRUPO_MEMBROS" ADD CONSTRAINT "TR_GRUPO_MEMBROS_COD_GRUPO_ID_fkey" FOREIGN KEY ("COD_GRUPO_ID") REFERENCES "TA_GRUPO"("COD_GRUPO_ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TR_GRUPO_MEMBROS" ADD CONSTRAINT "TR_GRUPO_MEMBROS_COD_USER_ID_fkey" FOREIGN KEY ("COD_USER_ID") REFERENCES "TP_USER"("COD_USER_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- Backfill: dono = usuário criador para grupos existentes
UPDATE "TA_GRUPO" SET "COD_USUARIO_DONO" = "COD_USUARIO_CRIACAO" WHERE "COD_USUARIO_DONO" IS NULL;
